"use client"
// import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import { Provider, useSelector } from 'react-redux';
import { AuthenticationProvider } from "@ui/components/authentication.provider";
import DialogProvider from "@ui/components/dialog.provider";
import ToastProvider from "@ui/components/toast.provider";

import AppStore, { RootState } from '@/ui/store/app.store';

import "./globals.css";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider store={AppStore}>
          <Theme accentColor="green" grayColor="sage">
            <ToastProvider><div>a</div></ToastProvider>
            <DialogProvider>
              <AuthenticationProvider>{children}</AuthenticationProvider>
            </DialogProvider>
          </Theme>
        </Provider>
      </body>
    </html>
  );
}
