import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import "./globals.css";
import { AuthenticationProvider } from "@presentation/components/authentication.provider";
import DialogProvider from "@presentation/components/dialog.provider";
import ToastProvider from "@/presentation/components/toast.provider";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme accentColor="green" grayColor="sage">
          <ToastProvider>
            <DialogProvider>
              <AuthenticationProvider>{children}</AuthenticationProvider>
            </DialogProvider>
          </ToastProvider>
        </Theme>
      </body>
    </html>
  );
}
