import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import "./globals.css";
import { AuthenticationProvider } from "@/ui/Common/providers/authentication.provider";
import DialogProvider from "@/ui/Common/components/DialogProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme accentColor="green" grayColor="sage">
          <AuthenticationProvider>{children}</AuthenticationProvider>
          <DialogProvider />
        </Theme>
      </body>
    </html>
  );
}
