
import {
  Alignment,
  AutoLink,
  AutoImage,
  Autosave,
  BalloonToolbar,
  BlockQuote,
  BlockToolbar,
  Bold,
  Code,
  Essentials,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  Heading,
  ImageBlock,
  ImageCaption,
  ImageInline,
  ImageInsert,
  ImageInsertViaUrl,
  ImageResize,
  ImageStyle,
  ImageTextAlternative,
  ImageToolbar,
  ImageUpload,
  Highlight,
  HorizontalLine,
  Indent,
  IndentBlock,
  Italic,
  Link,
  LinkImage,
  List,
  Paragraph,
  RemoveFormat,
  SpecialCharacters,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableCaption,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  TableToolbar,
  Underline,
  TodoList,
} from "ckeditor5";
import { UploadAdapterPlugin } from "./UploadAdapter";
import ExtendedImagePlugin from "./image-plugin";

export const CKEditorConfig = {
  toolbar: {
    viewportTopOffset: -100,
    items: [
      "heading",
      "|",
      "fontSize",
      "fontFamily",
      "fontColor",
      "fontBackgroundColor",
      "|",
      "bold",
      "italic",
      "underline",
      "strikethrough",
      // "subscript",
      // "superscript",
      // "code",
      "removeFormat",
      "|",
      // "specialCharacters",
      "horizontalLine",
      "link",
      'insertImage',
      "insertTable",
      "highlight",
      "blockQuote",
      "|",
      "alignment",
      "|",
      "outdent",
      "indent",
      "|",
      'numberedList', 'bulletedList', 'todoList'
    ],
    shouldNotGroupWhenFull: false,
  },
  plugins: [
    Alignment,
    AutoImage,
    AutoLink,
    Autosave,
    BalloonToolbar,
    BlockQuote,
    BlockToolbar,
    Bold,
    Code,
    Essentials,
    FontBackgroundColor,
    FontColor,
    FontFamily,
    FontSize,
    Heading,
    ImageBlock,
    ImageCaption,
    ImageInline,
    ImageInsert,
    ImageInsertViaUrl,
    ImageResize,
    ImageStyle,
    ImageTextAlternative,
    ImageToolbar,
    ImageUpload,
    Highlight,
    HorizontalLine,
    Indent,
    IndentBlock,
    Italic,
    Link,
    LinkImage,
    List,
    Paragraph,
    RemoveFormat,
    SpecialCharacters,
    Strikethrough,
    Subscript,
    Superscript,
    Table,
    TableCaption,
    TableCellProperties,
    TableColumnResize,
    TableProperties,
    TableToolbar,
    Underline,
    TodoList,

    UploadAdapterPlugin,
    ExtendedImagePlugin,
  ],
  balloonToolbar: ["bold", "italic", "|", "link"],
  blockToolbar: [
    "fontSize",
    "fontColor",
    "fontBackgroundColor",
    "|",
    "bold",
    "italic",
    "|",
    "link",
    "insertImage",
    "insertTable",
    "|",
    "outdent",
    "indent",
    "|",
    'numberedList', 'bulletedList', 'todoList'
  ],
  image: {
    toolbar: [
      'imageStyle:inline',
      'imageStyle:block',
      'imageStyle:side',
      '|',
      'resizeImage',
      '|',
      'toggleImageCaption',
      'imageTextAlternative',
      '|',
      'linkImage'
    ],
    insert: {
      integrations: ['assetManager', 'upload', 'url']
    }
  },
  fontFamily: {
    options: [
      'default',
      'Arial, Helvetica, sans-serif',
      '\'Courier New\', Courier, monospace',
      '\'Lucida Sans Unicode\', \'Lucida Grande\', sans-serif',
      'Tahoma, Geneva, sans-serif',
      'Verdana, Geneva, sans-serif',
    ],
    supportAllValues: true,
  },
  fontSize: {
    options: [10, 12, 14, "default", 18, 20, 22],
    supportAllValues: true,
  },
  heading: {
    options: [
      { model: 'paragraph', title: 'Paragraph', class: 'ck-heading-paragraph', view: { name: 'p', classes: 'ck-heading-paragraph'} },
      { model: 'heading1', view: { name: 'h1', classes: 'ck-heading-heading1'}, title: 'Heading 1', class: 'ck-heading-heading1', },
      { model: 'heading2', view: { name: 'h2', classes: 'ck-heading-heading2'}, title: 'Heading 2', class: 'ck-heading-heading2', },
      { model: 'heading3', view: { name: 'h3', classes: 'ck-heading-heading3'}, title: 'Heading 3', class: 'ck-heading-heading3', },
      { model: 'heading4', view: { name: 'h4', classes: 'ck-heading-heading4'}, title: 'Heading 4', class: 'ck-heading-heading4', },
    ]
  },
  licenseKey: 'GPL',
  link: {
    addTargetToExternalLinks: true,
    defaultProtocol: "https://",
    decorators: {
      toggleDownloadable: {
        mode: "manual",
        label: "Downloadable",
        attributes: {
          download: "file",
        },
      },
    },
  },
  placeholder: "Type or paste your content here!",
  table: {
    contentToolbar: [
      "tableColumn",
      "tableRow",
      "mergeTableCells",
      "tableProperties",
      "tableCellProperties",
    ],
  },
}