services:
    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: php
        build: ./php
        ports:
            - 5173:5173
        environment:
            - NODE_OPTIONS=--max-old-space-size=4096
        volumes:
            - ../laravel:/var/www:cached
            - ../package:/var/package

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - 8080:80
        volumes:
            - ../laravel:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    ####################################################################################################
    # Node
    ####################################################################################################
    # node:
    #     image: node
    #     container_name: node
    #     volumes:
    #         - ../package:/home/node/app
    #     working_dir: /var/www/html
    #     ports:
    #         - 3000:3000
    #         - 3001:3001
    #     command: bash -c "npm install && npm run dev"

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    # db:
    #     image: mysql:8.1
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - ./db/data:/var/lib/mysql
    #         - ./logs:/var/log/mysql
    #         - ./db/sql:/docker-entrypoint-initdb.d
    #     container_name: mysql
    #     restart: always
    #     environment:
    #         MYSQL_DATABASE: ${DB_DATABASE}
    #         MYSQL_USER: ${DB_USERNAME}
    #         MYSQL_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8081:80
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        volumes:
            - ./phpmyadmin/sessions:/sessions

    ####################################################################################################
    # Adminer
    ####################################################################################################
    # adminer:
    #     image: adminer
    #     ports:
    #         - 9090:8080
    #     depends_on:
    #     - db

    ####################################################################################################
    # Mailpit
    ####################################################################################################
    # mail:
    #     image: axllent/mailpit:latest
    #     ports:
    #     - 8025:8025
    #     - 1025:1025

    ####################################################################################################
    # Redis
    ####################################################################################################
    # redis:
    #     image: redis:latest
    #     command: redis-server --appendonly yes
    #     volumes:
    #     - ./redis/data:/data
    #     ports:
    #     - 6379:6379

    # ####################################################################################################
    # # DATABASE (MariaDB)
    # ####################################################################################################
    db:
        image: mariadb:10.11
        container_name: mariadb
        ports:
            - 3306:3306
        volumes:
            - ./db/data:/var/lib/mysql
            - ./logs:/var/log/mysql
            - ./db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ####################################################################################################
    # PostgreSQL
    ####################################################################################################
    # db:
    #     image: postgres:16
    #     ports:
    #         - 5432:5432
    #     volumes:
    #         - ./db/data:/var/lib/postgresql/data
    #         - ./db/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         - POSTGRES_USER=refactorian
    #         - POSTGRES_PASSWORD=refactorian
    #         - POSTGRES_DB=refactorian

    ####################################################################################################
    # pgAdmin
    ####################################################################################################
    # pgadmin:
    #     image: dpage/pgadmin4
    #     ports:
    #         - 5050:80
    #     environment:
    #         - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    #         - PGADMIN_DEFAULT_PASSWORD=password
    #     depends_on:
    #         - db
